models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(150))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100), unique=True)
    
    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.secret_key = 'SecretKey'
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:admin123*@localhost/contactsdb'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint("contacts", __name__)


@contacts.route("/")
def home():
    contacts = Contact.query.all()
    return render_template("index.html", contacts=contacts)


@contacts.route("/new", methods=["POST"])
def add_contact():

    full_name = request.form["full_name"]
    email = request.form["email"]
    phone = request.form["phone"]

    new_contact = Contact(fullname=full_name, email=email, phone=phone)

    db.session.add(new_contact)
    db.session.commit()
    
    flash('Contact added successfully')

    return redirect(url_for("contacts.home"))


@contacts.route("/update/<id>", methods=["POST", "GET"])
def update(id):
    
    contact = Contact.query.get(id)
    
    if request.method == 'POST':
        contact.fullname = request.form['full_name']
        contact.email = request.form['email']
        contact.phone = request.form['phone']

        db.session.commit()
        
        flash('Contact updated successfully')
        
        return redirect(url_for("contacts.home"))    

    return render_template("update.html", contact=contact)


@contacts.route("/delete/<id>")
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    
    flash('Contact deleted successfully')
    
    return redirect(url_for("contacts.home"))

templates/index.html
{% with messages = get_flashed_messages() %}

  {% if messages %}
    {% for message in messages%}
      {{message}}
    {% endfor %}
  {% endif %}

{% endwith %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home Page</title>
    <meta charset="utf-8" />
  </head>
  <body>
    <h1>Home Page</h1>
    <form action='/new' method='POST'>
        <label for ='full_name'>Full Name</label><input type = 'text' id='full_name' name='full_name'/>
        <label for ='email'>Email</label><input type = 'email' id='email' name='email' />
        <label for ='phone'>Phone</label><input type = 'text' id='phone' name='phone' /> 
        
        <button>Submit</button>
    </form>
    <div>
      {% for contact in contacts %}
      <div>
        <h5>{{ contact.fullname }} </h5>
        <a href='{{ url_for('contacts.update', id=contact.id) }}'>Update</a>
        <a href=' {{ url_for('contacts.delete', id=contact.id) }}'>Delete</a>
        <p>{{ contact.phone }}</p>
        <p>{{contact.email}}</p>
      </div>
      {% endfor %}

    </div>
  </body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home Page</title>
    <meta charset="utf-8" />
  </head>
  <body>
    <h1>Home Page</h1>

    <form action="/update/{{contact.id}}" method="POST">
      <label for="full_name">Full Name</label
      ><input
        type="text"
        id="full_name"
        name="full_name"
        ,
        value="{{contact.fullname}}"
      />
      <label for="email">Email</label
      ><input type="email" id="email" name="email" value="{{contact.email}}" />
      <label for="phone">Phone</label
      ><input type="text" id="phone" name="phone" value="{{contact.phone}}" />

      <button>Submit</button>
    </form>
  </body>
</html>